### ISSUE TITLE
Small bug at demo page

### ISSUE THREAD

**Issue by sshyran** [netgfx/SplitText#2]
Big green 'Download' button at [demo page ](http://www.netgfx.com/trunk/splitText/examples/examples.html) currently does not point to any file download (just blank bage at [github repo](https://github.com/netgfx/splittext/archives/master))

**Comment by netgfx** [comment]
Yes Github removed the download functionality but you can still download from the main Gighub repo. or here: https://github.com/netgfx/SplitText/archive/master.zip
